export interface ChapterConfig {
  number: number;
  title: string;
  description: string;
  primaryColor: string;
  prevLink?: string;
  nextLink?: string;
  prevText?: string;
  nextText?: string;
  ctaTitle?: string;
  ctaDescription?: string;
  ctaPrimaryText?: string;
  ctaPrimaryLink?: string;
  ctaSecondaryText?: string;
  ctaSecondaryLink?: string;
}

export const chapters: ChapterConfig[] = [
  {
    number: 1,
    title: "Bakteriološki praktikum",
    description: "Osnovna pravila, tehnike i oprema u bakteriološkom praktikumu. Upoznajte se s sigurnosnim mjerama i aseptičkim tehnikama.",
    primaryColor: "green",
    prevLink: "/predgovor/",
    nextLink: "/poglavlje-2/",
    prevText: "← Predgovor",
    nextText: "Poglavlje 2 →",
    ctaTitle: "Spreman za praktične vježbe?",
    ctaDescription: "Nastavite s učenjem i započnite s praktičnim vježbama iz bakteriološkog praktikuma.",
    ctaPrimaryText: "Započni vježbe",
    ctaPrimaryLink: "/vjezba-1/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 2,
    title: "Sterilizacija",
    description: "Metode i postupci sterilizacije u bakteriološkom praktikumu",
    primaryColor: "blue",
    prevLink: "/poglavlje-1/",
    nextLink: "/poglavlje-3/",
    prevText: "← Poglavlje 1",
    nextText: "Poglavlje 3 →",
    ctaTitle: "Spreman za sljedeće poglavlje?",
    ctaDescription: "Nastavite s učenjem o metodama bojenja bakterija u sljedećem poglavlju.",
    ctaPrimaryText: "Poglavlje 3",
    ctaPrimaryLink: "/poglavlje-3/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 3,
    title: "Metode bojenja bakterija",
    description: "Različite tehnike bojenja za identifikaciju i karakterizaciju bakterijskih stanica",
    primaryColor: "purple",
    prevLink: "/poglavlje-2/",
    nextLink: "/poglavlje-4/",
    prevText: "← Poglavlje 2",
    nextText: "Poglavlje 4 →",
    ctaTitle: "Spreman za sljedeće poglavlje?",
    ctaDescription: "Nastavite s učenjem o pokretljivosti bakterija u sljedećem poglavlju.",
    ctaPrimaryText: "Poglavlje 4",
    ctaPrimaryLink: "/poglavlje-4/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 4,
    title: "Pokretljivost bakterija",
    description: "Ispitivanje pokretljivosti bakterija i razumijevanje mehanizama kretanja",
    primaryColor: "yellow",
    prevLink: "/poglavlje-3/",
    nextLink: "/poglavlje-5/",
    prevText: "← Poglavlje 3",
    nextText: "Poglavlje 5 →",
    ctaTitle: "Spreman za sljedeće poglavlje?",
    ctaDescription: "Nastavite s učenjem o biokemijskim svojstvima bakterija u sljedećem poglavlju.",
    ctaPrimaryText: "Poglavlje 5",
    ctaPrimaryLink: "/poglavlje-5/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 5,
    title: "Biokemijska svojstva bakterija",
    description: "Testovi za određivanje biokemijskih karakteristika i metabolizma bakterija",
    primaryColor: "red",
    prevLink: "/poglavlje-4/",
    nextLink: "/poglavlje-6/",
    prevText: "← Poglavlje 4",
    nextText: "Poglavlje 6 →",
    ctaTitle: "Spreman za sljedeće poglavlje?",
    ctaDescription: "Nastavite s učenjem o određivanju broja bakterija u sljedećem poglavlju.",
    ctaPrimaryText: "Poglavlje 6",
    ctaPrimaryLink: "/poglavlje-6/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 6,
    title: "Određivanje broja bakterija - indirektne metode",
    description: "Indirektne metode brojanja bakterija u suspenziji i procjena brojnosti",
    primaryColor: "indigo",
    prevLink: "/poglavlje-5/",
    nextLink: "/poglavlje-7/",
    prevText: "← Poglavlje 5",
    nextText: "Poglavlje 7 →",
    ctaTitle: "Spreman za sljedeće poglavlje?",
    ctaDescription: "Nastavite s učenjem o direktnim metodama brojanja bakterija u sljedećem poglavlju.",
    ctaPrimaryText: "Poglavlje 7",
    ctaPrimaryLink: "/poglavlje-7/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 7,
    title: "Određivanje broja bakterija - direktne metode",
    description: "Direktne metode brojanja bakterija i mikroskopske tehnike analize",
    primaryColor: "pink",
    prevLink: "/poglavlje-6/",
    nextLink: "/poglavlje-8/",
    prevText: "← Poglavlje 6",
    nextText: "Poglavlje 8 →",
    ctaTitle: "Spreman za sljedeće poglavlje?",
    ctaDescription: "Nastavite s učenjem o bakterijama indikatorima sanitarnog stanja u sljedećem poglavlju.",
    ctaPrimaryText: "Poglavlje 8",
    ctaPrimaryLink: "/poglavlje-8/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 8,
    title: "Bakterije indikatori sanitarnog stanja",
    description: "Bakterije kao indikatori sanitarnog stanja sredine i sigurnosti",
    primaryColor: "teal",
    prevLink: "/poglavlje-7/",
    nextLink: "/poglavlje-9/",
    prevText: "← Poglavlje 7",
    nextText: "Poglavlje 9 →",
    ctaTitle: "Spreman za sljedeće poglavlje?",
    ctaDescription: "Nastavite s učenjem o sanitarnoj bakteriološkoj analizi vode u sljedećem poglavlju.",
    ctaPrimaryText: "Poglavlje 9",
    ctaPrimaryLink: "/poglavlje-9/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 9,
    title: "Sanitarna bakteriološka analiza vode",
    description: "Metode analize kvalitete vode i određivanja sanitarnog stanja",
    primaryColor: "cyan",
    prevLink: "/poglavlje-8/",
    nextLink: "/poglavlje-10/",
    prevText: "← Poglavlje 8",
    nextText: "Poglavlje 10 →",
    ctaTitle: "Spreman za sljedeće poglavlje?",
    ctaDescription: "Nastavite s učenjem o termofilnim bakterijama u sljedećem poglavlju.",
    ctaPrimaryText: "Poglavlje 10",
    ctaPrimaryLink: "/poglavlje-10/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 10,
    title: "Termofilne bakterije",
    description: "Karakterizacija i ispitivanje bakterija koje rastu na visokim temperaturama",
    primaryColor: "orange",
    prevLink: "/poglavlje-9/",
    nextLink: "/poglavlje-11/",
    prevText: "← Poglavlje 9",
    nextText: "Poglavlje 11 →",
    ctaTitle: "Spreman za sljedeće poglavlje?",
    ctaDescription: "Nastavite s učenjem o aerobnim sporogenim bakterijama u sljedećem poglavlju.",
    ctaPrimaryText: "Poglavlje 11",
    ctaPrimaryLink: "/poglavlje-11/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 11,
    title: "Aerobne sporogene bakterije",
    description: "Ispitivanje aerobnih bakterija koje stvaraju spore i njihove karakteristike",
    primaryColor: "lime",
    prevLink: "/poglavlje-10/",
    nextLink: "/poglavlje-12/",
    prevText: "← Poglavlje 10",
    nextText: "Poglavlje 12 →",
    ctaTitle: "Spreman za sljedeće poglavlje?",
    ctaDescription: "Nastavite s učenjem o anaerobnim bakterijama u sljedećem poglavlju.",
    ctaPrimaryText: "Poglavlje 12",
    ctaPrimaryLink: "/poglavlje-12/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 12,
    title: "Anaerobne bakterije",
    description: "Tehnike rada s anaerobnim bakterijama i posebni uvjeti kultivacije",
    primaryColor: "emerald",
    prevLink: "/poglavlje-11/",
    nextLink: "/poglavlje-13/",
    prevText: "← Poglavlje 11",
    nextText: "Poglavlje 13 →",
    ctaTitle: "Spreman za sljedeće poglavlje?",
    ctaDescription: "Nastavite s učenjem o izradi antibiograma i aromatograma u sljedećem poglavlju.",
    ctaPrimaryText: "Poglavlje 13",
    ctaPrimaryLink: "/poglavlje-13/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 13,
    title: "Izrada antibiograma i aromatograma",
    description: "Testiranje osjetljivosti bakterija na antibiotike i aromatske spojeve",
    primaryColor: "violet",
    prevLink: "/poglavlje-12/",
    nextLink: "/poglavlje-14/",
    prevText: "← Poglavlje 12",
    nextText: "Poglavlje 14 →",
    ctaTitle: "Spreman za sljedeće poglavlje?",
    ctaDescription: "Nastavite s učenjem o testu toksičnosti s kvascem u sljedećem poglavlju.",
    ctaPrimaryText: "Poglavlje 14",
    ctaPrimaryLink: "/poglavlje-14/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 14,
    title: "Test toksičnosti s kvascem",
    description: "Ispitivanje toksičnosti različitih spojeva pomoću kvasaca kao modela",
    primaryColor: "rose",
    prevLink: "/poglavlje-13/",
    nextLink: "/poglavlje-15/",
    prevText: "← Poglavlje 13",
    nextText: "Poglavlje 15 →",
    ctaTitle: "Spreman za sljedeće poglavlje?",
    ctaDescription: "Nastavite s učenjem o bakteriološkom ispitivanju kvalitete namirnica u sljedećem poglavlju.",
    ctaPrimaryText: "Poglavlje 15",
    ctaPrimaryLink: "/poglavlje-15/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 15,
    title: "Bakteriološko ispitivanje kvalitete namirnica",
    description: "Metode analize kvalitete namirnica i sigurnosti hrane",
    primaryColor: "sky",
    prevLink: "/poglavlje-14/",
    nextLink: "/poglavlje-16/",
    prevText: "← Poglavlje 14",
    nextText: "Poglavlje 16 →",
    ctaTitle: "Spreman za sljedeće poglavlje?",
    ctaDescription: "Nastavite s učenjem o bakterijama mliječne fermentacije u sljedećem poglavlju.",
    ctaPrimaryText: "Poglavlje 16",
    ctaPrimaryLink: "/poglavlje-16/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 16,
    title: "Bakterije mliječne fermentacije",
    description: "Karakterizacija bakterija mliječne fermentacije i njihove primjene",
    primaryColor: "amber",
    prevLink: "/poglavlje-15/",
    nextLink: "/poglavlje-17/",
    prevText: "← Poglavlje 15",
    nextText: "Poglavlje 17 →",
    ctaTitle: "Spreman za sljedeće poglavlje?",
    ctaDescription: "Nastavite s učenjem o biogeokemijskom ciklusu ugljika u sljedećem poglavlju.",
    ctaPrimaryText: "Poglavlje 17",
    ctaPrimaryLink: "/poglavlje-17/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 17,
    title: "Biogeokemijski ciklus ugljika",
    description: "Uloga bakterija u biogeokemijskom ciklusu ugljika i globalnim procesima",
    primaryColor: "green",
    prevLink: "/poglavlje-16/",
    nextLink: "/poglavlje-18/",
    prevText: "← Poglavlje 16",
    nextText: "Poglavlje 18 →",
    ctaTitle: "Spreman za sljedeće poglavlje?",
    ctaDescription: "Nastavite s učenjem o biogeokemijskom ciklusu dušika u sljedećem poglavlju.",
    ctaPrimaryText: "Poglavlje 18",
    ctaPrimaryLink: "/poglavlje-18/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 18,
    title: "Biogeokemijski ciklus dušika",
    description: "Bakterije u biogeokemijskom ciklusu dušika i fiksaciji dušika",
    primaryColor: "blue",
    prevLink: "/poglavlje-17/",
    nextLink: "/poglavlje-19/",
    prevText: "← Poglavlje 17",
    nextText: "Poglavlje 19 →",
    ctaTitle: "Spreman za sljedeće poglavlje?",
    ctaDescription: "Nastavite s učenjem o biogeokemijskom ciklusu sumpora u sljedećem poglavlju.",
    ctaPrimaryText: "Poglavlje 19",
    ctaPrimaryLink: "/poglavlje-19/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 19,
    title: "Biogeokemijski ciklus sumpora",
    description: "Uloga bakterija u biogeokemijskom ciklusu sumpora i redukciji sulfata",
    primaryColor: "purple",
    prevLink: "/poglavlje-18/",
    nextLink: "/poglavlje-20/",
    prevText: "← Poglavlje 18",
    nextText: "Poglavlje 20 →",
    ctaTitle: "Spreman za sljedeće poglavlje?",
    ctaDescription: "Nastavite s učenjem o biogeokemijskom ciklusu fosfora u sljedećem poglavlju.",
    ctaPrimaryText: "Poglavlje 20",
    ctaPrimaryLink: "/poglavlje-20/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 20,
    title: "Biogeokemijski ciklus fosfora",
    description: "Bakterije u biogeokemijskom ciklusu fosfora i solubilizaciji fosfata",
    primaryColor: "yellow",
    prevLink: "/poglavlje-19/",
    nextLink: "/poglavlje-21/",
    prevText: "← Poglavlje 19",
    nextText: "Poglavlje 21 →",
    ctaTitle: "Spreman za sljedeće poglavlje?",
    ctaDescription: "Nastavite s učenjem o metodi otiska u sljedećem poglavlju.",
    ctaPrimaryText: "Poglavlje 21",
    ctaPrimaryLink: "/poglavlje-21/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 21,
    title: "Metoda otiska",
    description: "Tehnika otiska za ispitivanje mikrobioma površina i materijala",
    primaryColor: "red",
    prevLink: "/poglavlje-20/",
    nextLink: "/poglavlje-22/",
    prevText: "← Poglavlje 20",
    nextText: "Poglavlje 22 →",
    ctaTitle: "Spreman za sljedeće poglavlje?",
    ctaDescription: "Nastavite s učenjem o streptomicetima u sljedećem poglavlju.",
    ctaPrimaryText: "Poglavlje 22",
    ctaPrimaryLink: "/poglavlje-22/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 22,
    title: "Streptomiceti",
    description: "Karakterizacija streptomiceta i njihove uloge u proizvodnji antibiotika",
    primaryColor: "indigo",
    prevLink: "/poglavlje-21/",
    nextLink: "/poglavlje-23/",
    prevText: "← Poglavlje 21",
    nextText: "Poglavlje 23 →",
    ctaTitle: "Spreman za sljedeće poglavlje?",
    ctaDescription: "Nastavite s učenjem o izolaciji anaerobnih fototrofnih bakterija u sljedećem poglavlju.",
    ctaPrimaryText: "Poglavlje 23",
    ctaPrimaryLink: "/poglavlje-23/",
    ctaSecondaryText: "Povratak na sadržaj",
    ctaSecondaryLink: "/sadrzaj/"
  },
  {
    number: 23,
    title: "Izolacija anaerobnih fototrofnih bakterija",
    description: "Specijalizirane tehnike za izolaciju anaerobnih fototrofnih bakterija",
    primaryColor: "pink",
    prevLink: "/poglavlje-22/",
    prevText: "← Poglavlje 22",
    ctaTitle: "Čestitamo!",
    ctaDescription: "Završili ste sva poglavlja udžbenika iz bakteriologije. Nastavite s praktičnim vježbama i provjerom znanja.",
    ctaPrimaryText: "Povratak na sadržaj",
    ctaPrimaryLink: "/sadrzaj/",
    ctaSecondaryText: "Povratak na početnu",
    ctaSecondaryLink: "/"
  }
];

export function getChapterConfig(number: number): ChapterConfig | undefined {
  return chapters.find(chapter => chapter.number === number);
}
